### ISSUE TITLE
Счетчик - это универсальное решение, но это лишние итерации. Можешь запросить длину списка?

### ISSUE THREAD

**Issue by denis-trofimov** [slychai85/Python#1]
https://github.com/slychai85/Python/blob/36196bec432384ed5caec4c95ca1510a0402b4b0/Learn_Python/home_work_week_2/work_for.py#L81-L83

**Comment by denis-trofimov** [comment]
здесь у тебя в двух местах логика такая, можно оптимизировать!

**Comment by slychai85** [comment]
Исправил замечания.

**Comment by denis-trofimov** [comment]
Можешь запросить длину списка? len(school_class['scores']) как и где можно использовать?
- окей увидел. 
print('В вашем классе "{}" средний балл учеников: {:.1f}'.format(class_name, **average( average_class, count )** ) )

кол-во классов тоже чей-то len() ?

Зачем дважды два вложенных цикла? Ты делаешь 2 * classes * marks сложений, а можно classes * marks и посчитать и вывести оба вида средних.

**Comment by slychai85** [comment]
Не все понял в последнем комментарии, но исправил. Объединил два цикла в один.

**Comment by slychai85** [comment]
Оптимизировал задание

**Comment by denis-trofimov** [comment]
проверил
