### ISSUE TITLE
Обработчик эха не сработал, проверено.

### ISSUE THREAD

**Issue by denis-trofimov** [slychai85/Python#3]
https://github.com/slychai85/Python/blob/36196bec432384ed5caec4c95ca1510a0402b4b0/Learn_Python/home_work_week_2/work_bot.py#L103-L104

**Comment by slychai85** [comment]
Удалил этот рудимент.

**Comment by denis-trofimov** [comment]
можно было обе функции сделать рабочими одновременно.

**Comment by slychai85** [comment]
Уже сил нет. Очень интенсивная неделя.
